import React from "react";
// import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { Toaster } from "react-hot-toast";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Erick Pham - App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}): React.ReactNode => (
  <html lang="en">
    <body>
      <ThemeRegistry>
        <Toaster position="bottom-center" />
        {children}
      </ThemeRegistry>
    </body>
  </html>
);

export default RootLayout;
