import React from "react";
import { ConfigProvider, Layout } from "antd";
import { Footer, Content } from "antd/es/layout/layout";

export const metadata = {
  title: "Erick Pham - App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<React.PropsWithChildren> = ({
  children,
}: React.PropsWithChildren) => (
  <ConfigProvider>
    <Layout>
      <Content style={{ padding: "0 48px" }}>
        <div>{children}</div>
      </Content>
      <Footer style={{ textAlign: "center" }}>
        Ant Design ©2023 Created by Ant UED
      </Footer>
    </Layout>
  </ConfigProvider>
);

export default RootLayout;
